name: Build and push image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      update_latest:
        required: false
        type: boolean
      is_preview:
        required: false
        type: boolean
      build_path:
        required: false
        type: string
        default: "."
      docker_buildkit:
        required: false
        type: boolean
        default: false
    secrets:
      gh_token:
        required: false
      aws_access_key_id:
        required: true
      aws_secret_acesss_key:
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_acesss_key }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd ${{ inputs.build_path }}
          if ${{ inputs.is_preview }}
          then
            TAG=pr-${{github.event.number}}-${{github.event.pull_request.head.sha}}
          else
            TAG=$(grep 'version:' chart/Chart.yaml | tail -n1 | awk '{ print $2}')
          fi

          echo "Docker buildkit: ${{ inputs.docker_buildkit }}"

          if [ "${{ inputs.gh_token }}" != "" ]; then
            echo "Token found"
            DOCKER_BUILDKIT=${{ inputs.docker_buildkit }} docker build --build-arg GH_TOKEN=${{ secrets.gh_token }} -t $ECR_REGISTRY/${{ inputs.image_name }}:$TAG .
          else
            echo "Token not found"
            DOCKER_BUILDKIT=${{ inputs.docker_buildkit }} docker build -t $ECR_REGISTRY/${{ inputs.image_name }}:$TAG .
          fi

          docker push $ECR_REGISTRY/${{ inputs.image_name }}:$TAG

          if ${{ inputs.update_latest }}
          then
            docker tag $ECR_REGISTRY/${{ inputs.image_name }}:$TAG $ECR_REGISTRY/${{ inputs.image_name }}:latest
            docker push $ECR_REGISTRY/${{ inputs.image_name }}:latest
          fi
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
